### ISSUE TITLE
miner.py

### ISSUE THREAD

**Issue by Anurag-Swarnim-Yadav** [Kolkir/cppminer#1]
Hey

When running miner.py and giving path and output. I am getting the following error.   

 if len(self.samples) > 0:
AttributeError: 'AstParser' object has no attribute 'samples'

How to fix this?

**Comment by Kolkir** [comment]
@Anurag-Swarnim-Yadav It means that the AstParser object didn't find any C++ functions in files placed in the input directory. Could you show the structure of the input directory?

**Comment by Anurag-Swarnim-Yadav** [comment]
@Kolkir  

<img width="726" alt="Screen Shot 2020-04-18 at 12 37 36 AM" src="https://user-images.githubusercontent.com/27738464/79629204-0bc15900-810d-11ea-80fe-86ef0d592b4f.png">

<img width="629" alt="Screen Shot 2020-04-18 at 12 38 02 AM" src="https://user-images.githubusercontent.com/27738464/79629208-17148480-810d-11ea-896a-eda943d7257d.png">


<img width="743" alt="Screen Shot 2020-04-18 at 12 38 35 AM" src="https://user-images.githubusercontent.com/27738464/79629209-1a0f7500-810d-11ea-9193-f7b26830b4c5.png">

**Comment by Anurag-Swarnim-Yadav** [comment]
@Kolkir So I created an input folder and within that folder I have test.cpp

I am running the following command:

python3 miner.py input/ output/

**Comment by Anurag-Swarnim-Yadav** [comment]
@Kolkir 

<img width="583" alt="Screen Shot 2020-04-18 at 12 46 35 AM" src="https://user-images.githubusercontent.com/27738464/79629294-1c260380-810e-11ea-90bc-e50f45f853bd.png">

**Comment by Anurag-Swarnim-Yadav** [comment]
so I have a test.cpp file under input directory and I am running the following command:

python3 miner.py input/ output/

**Comment by Kolkir** [comment]
@Anurag-Swarnim-Yadav I think the problem is that the libclang can't parse correctly your function because it doesn't know where to find the `iostream` header. If you use external libraries(standard library is also external) in the code you need to put compilation database with correct compilation commands including all include paths.

**Comment by Anurag-Swarnim-Yadav** [comment]
@Kolkir 

I just removed the iostream header and my current test.cpp has 

int main() {
    std::cout << "Hello World!";
    return 0;
}

but I am still getting the same error.

**Comment by Kolkir** [comment]
@Anurag-Swarnim-Yadav now you have the undeclared item `std::cout`

**Comment by Kolkir** [comment]
@Anurag-Swarnim-Yadav Please consider to try the `data` folder from the original repository for initial experiments

**Comment by Anurag-Swarnim-Yadav** [comment]
The CMakeLists.txt in the data folder. Do I have to run that first? if yes then what exactly do I need to run ?

Thanks

**Comment by Anurag-Swarnim-Yadav** [comment]
@Kolkir 

root@cd947fd6af0f:/anurag/cppminer/src# python3 miner.py data/ output/
Parallel processes num: 4
Max contexts num: 100
Max path length: 0
Max sub-tokens num: 5
Max AST depth: 0
Input path: /anurag/cppminer/src/data
Output path: /anurag/cppminer/src/output
Parsing files ...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/clang/cindex.py", line 4129, in get_cindex_library
    library = cdll.LoadLibrary(self.get_filename())
  File "/usr/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libclang.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "miner.py", line 144, in <module>
    main()
  File "miner.py", line 117, in main
    for _ in range(parallel_processes_num)]
  File "miner.py", line 117, in <listcomp>
    for _ in range(parallel_processes_num)]
  File "/anurag/cppminer/src/parser_process.py", line 21, in __init__
    self.parser = AstParser(max_contexts_num, max_path_len, max_subtokens_num, max_ast_depth, output_path)
  File "/anurag/cppminer/src/cpp_parser/ast_parser.py", line 49, in __init__
    self.index = Index.create()
  File "/usr/local/lib/python3.6/dist-packages/clang/cindex.py", line 2666, in create
    return Index(conf.lib.clang_createIndex(excludeDecls, 0))
  File "/usr/local/lib/python3.6/dist-packages/clang/cindex.py", line 198, in __get__
    value = self.wrapped(instance)
  File "/usr/local/lib/python3.6/dist-packages/clang/cindex.py", line 4103, in lib
    lib = self.get_cindex_library()
  File "/usr/local/lib/python3.6/dist-packages/clang/cindex.py", line 4134, in get_cindex_library
    raise LibclangError(msg)
clang.cindex.LibclangError: libclang.so: cannot open shared object file: No such file or directory. To provide a path to libclang use Config.set_library_path() or Config.set_library_file().
Exception ignored in: <bound method AstParser.__del__ of <cpp_parser.ast_parser.AstParser object at 0x7faf6543def0>>
Traceback (most recent call last):
  File "/anurag/cppminer/src/cpp_parser/ast_parser.py", line 54, in __del__
    self.save()
  File "/anurag/cppminer/src/cpp_parser/ast_parser.py", line 93, in save
    if len(self.samples) > 0:
AttributeError: 'AstParser' object has no attribute 'samples'


I just ran the data folder and I still have the same issue

**Comment by Kolkir** [comment]
@Anurag-Swarnim-Yadav Notice the error `OSError: libclang.so: cannot open shared object file: No such file or directory` you didn't installed or configured the libclang.so library at all

**Comment by Anurag-Swarnim-Yadav** [comment]
@Kolkir  Seems like python is not able to find LibClang library. I tried to Config.set_library_path() but still not working. Do you have any idea about this? 

Thanks

**Comment by Kolkir** [comment]
May be the version of the python 'clang' package does not support the 'libclang.so' version? I've checked my code with Ubuntu and Arch Linux systems and everything worked fine.

**Comment by Anurag-Swarnim-Yadav** [comment]
@Kolkir 
could you please let me know your python and clang version. I will try to configure accordingly.

I am using:

Ubuntu 18.04.4 LTS \n \l
python - Python 3.6.9
clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu

Thanks

**Comment by Kolkir** [comment]
5.4.31-1-MANJARO
clang 9.0.1-1
Python 3.7
python clang package 6.0.0.2

**Comment by Anurag-Swarnim-Yadav** [comment]
@Kolkir 
Thanks for all the help. I got my issue resolved.  My next question to is : Should we expect raw files for all the input cpp files. I  am using the data provided by you in the data folder. After running miner.py I am getting 4 raw files but you have 5 .cpp files in data. I looked in the raw files. I can see that the miner function is not creating a raw file for the big_op.cc file. Do you have any idea why is it doing that?

**Comment by Kolkir** [comment]
@Anurag-Swarnim-Yadav cppminer doesn't create a raw file for each cpp file. You have 4 files just because you have a small number of cpp files and cppminer used 4 processing threads.

**Comment by Anurag-Swarnim-Yadav** [comment]
@Kolkir 
Thanks for answering. Just to be more clear you are saying that raw files created by cpp miner have the five files in it. It just the big_op.cc is small. Hence it has been added to other raw files. 

Also, could you please what do you mean by 4 processing threads?

**Comment by Kolkir** [comment]
@Anurag-Swarnim-Yadav cppminer can be configured to use several parallel threads(processes) for parsing by default is uses 4 threads. Also, there can be an arbitrary number of raw files after parsing, these files are used just as intermediated buffers for the merge utility.

**Comment by Anurag-Swarnim-Yadav** [comment]
@Kolkir 
Thanks a lot for all the feedback. Have a great day.

Thanks again
