### ISSUE TITLE
target label and context content

### ISSUE THREAD

**Issue by Anurag-Swarnim-Yadav** [Kolkir/cppminer#3]
@Kolkir 
Hi.  I hope you doing good. I have confusion with the target label and context path. After running miner.py. How can I differentiate between the target label and the context path? Also If I have my own label. How can I use my own label?

Thanks

**Comment by Kolkir** [comment]
Hi, the first chunk of each string in a file which goes before space is a target label. Please find dataset description in the code2seq  repository.

**Comment by Kolkir** [comment]
@Anurag-Swarnim-Yadav If you have additional questions please write me to the rotate@ukr.net. I'm closing this issue because it doesn't relate to the current application.
